name: Deploy Harvest Dev

on:
  push:
    branches:
      - "development"
    paths:
      - "*"

env:
  DOCKER_FILE: 'Source/Harvest/Dockerfile'
  DOCKER_IMAGE_TAG: 'shepherd/harvest'
  VERSION: 'fake-version'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Invoke build
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: BuildMicroserviceTest
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: ${{ github.event.sha }}
        inputs: '{ "dockerfile":"${{ env.DOCKER_FILE }}", "docker-image-tag":"${{ env.DOCKER_IMAGE_TAG }}", "version": "${{ env.VERSION }}" }'

    - name: Invoke deploy
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: DeployMicroserviceTest
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: ${{ github.event.sha }}
        inputs: '{ "dockerfile":"${{ env.DOCKER_FILE }}", "docker-image-tag":"${{ env.DOCKER_IMAGE_TAG }}", "version": "${{ env.VERSION }}" }'
