name: Deploy Harvest Dev

on:
  push:
    branches:
      - "development"
      - "master"

env:
  DOCKER_FILE: 'Source/Harvest/Dockerfile'
  DOCKER_IMAGE_TAG: 'shepherd/harvest'
  VERSION: 'fake-version'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Increment version
      uses: dolittle/increment-version-action@v2
      with:
        version: 6.0.0-development.51
        release-type: major